name: export-and-branch-solution

on:
  workflow_call:
    inputs:
      solution_name:
        description: 'name of the solution to worked on from Power Platform'
        required: true
      environment_url:
        description: 'url of the environment for export of the solution'
        required: true
      client_id:
        description: 'client id of the app registration'
        required: true
      tenant_id:
        description: 'tenant id of the app registration'
        required: true
    secrets:
      - APP_SECRET
      - PAT

env:
  SOLUTION_EXPORTED_FOLDER: out/exported/
  SOLUTION_FOLDER: out/solutions/
  SOLUTION_TARGET_FOLDER: solutions/

jobs:
  export-from-dev:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: ${{ inputs.environment_url }}
        app-id: ${{inputs.client_id}}
        client-secret: ${{ secrets.APP_SECRET }}
        tenant-id: ${{inputs.tenant_id}}


    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: ${{ inputs.environment_url }}
        app-id: ${{ inputs.client_id }}
        client-secret: ${{ secrets.APP_SECRET }}
        tenant-id: ${{inputs.tenant_id}}
        solution-name: ${{ inputs.solution_name }}
        solution-output-file: ${{ env.SOLUTION_EXPORTED_FOLDER}}/${{ inputs.solution_name }}.zip

    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: ${{ env.SOLUTION_EXPORTED_FOLDER}}/${{ inputs.solution_name }}.zip
        solution-folder: ${{ env.SOLUTION_FOLDER}}/${{ inputs.solution_name }}
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: branch-solution, prepare it for a PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@v0
      with:
        solution-folder: ${{ env.SOLUTION_FOLDER}}/${{ inputs.solution_name }}
        solution-target-folder: ${{ env.SOLUTION_TARGET_FOLDER}}/${{ inputs.solution_name }}
        repo-token: ${{ secrets.PAT }}
        allow-empty-commit: true